### ISSUE TITLE
AST Record Layout bug

### ISSUE THREAD

**Issue by ddkwork** [can1357/gengo#1]
```go

*** Dumping AST Record Layout
         0 | struct __NSConstantString_tag
         0 |   const int * isa
         8 |   int flags
        16 |   const char * str
        24 |   long length
           | [sizeof=32, align=8,
           |  nvsize=32, nvalign=8]


GOROOT=C:\Program Files\Go #gosetup
GOPATH=C:\Users\Admin\go #gosetup
"C:\Program Files\Go\bin\go.exe" test -c -o C:\Users\Admin\AppData\Local\JetBrains\GoLand2024.1\tmp\GoLand\___TestDemoDll_in_github_com_can1357_gengo_bind_demo.test.exe github.com/can1357/gengo/bind/demo #gosetup
"C:\Program Files\Go\bin\go.exe" tool test2json -t C:\Users\Admin\AppData\Local\JetBrains\GoLand2024.1\tmp\GoLand\___TestDemoDll_in_github_com_can1357_gengo_bind_demo.test.exe -test.v -test.paniconexit0 -test.run ^\QTestDemoDll\E$ #gosetup
2024-06-19 09:18:26    Trace ->  --------- title --------- │ ------------------ info ------------------ //runtime.doInit1+0xec C:/Program Files/Go/src/runtime/proc.go:7176
=== RUN   TestDemoDll
panic: input does not match format

goroutine 21 [running]:
github.com/ddkwork/golibrary/mylog.check[...](0x0?)
	D:/workspace/workspace/branch/golibrary/mylog/check.go:216 +0x186
github.com/ddkwork/golibrary/mylog.Check2[...](0x2, {0xccbf40, 0xc000280170?})
	D:/workspace/workspace/branch/golibrary/mylog/check.go:27 +0x45
github.com/can1357/gengo/clang.(*RecordLayout).UnmarshalString(0xc0002d0c00, {0xc00049401e?, 0xc1fbca?})
	D:/workspace/workspace/branch/gui/gengo/clang/layout_parse.go:78 +0x4c9
github.com/can1357/gengo/clang.(*LayoutMap).UnmarshalString(0xc00028e2c0, {0xc000494000?, 0x103?})
	D:/workspace/workspace/branch/gui/gengo/clang/layout_parse.go:145 +0x119
github.com/can1357/gengo/clang.ParseLayoutMap(...)
	D:/workspace/workspace/branch/gui/gengo/clang/layout_parse.go:156
github.com/can1357/gengo/clang.Parse.func2()
	D:/workspace/workspace/branch/gui/gengo/clang/invoke.go:82 +0x185
golang.org/x/sync/errgroup.(*Group).Go.func1()
	D:/desk/go/golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 19
	D:/desk/go/golang.org/x/sync@v0.7.0/errgroup/errgroup.go:75 +0x96


Process finished with the exit code 1

```

```go
we need:

func (r *RecordLayout) UnmarshalString(data string) error {
	// mylog.Check(errors.New("improperly terminated layout"))
	first := true
	for _, line := range strings.Split(data, "\n") {
		before, after, found := strings.Cut(line, "|")
		if !found {
			continue
		}

		// If before is empty, then it is the size and align.
		before = strings.TrimSpace(before)
		if before == "" {
			after = strings.TrimSpace(after)
			//mylog.Check2(fmt.Sscanf(after, "[sizeof=%d, align=%d]", &r.Size, &r.Align))
			mylog.Check2(fmt.Sscanf(after, "[sizeof=%d, align=%d", &r.Size, &r.Align))
			break
		}

```

remove "]"

**Comment by ddkwork** [comment]
Today I solved a bug in bitfield parsing, if you will, I will create pr
